[2023-05-11T05:11:41.202+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mongodb_backup.scp_to_server manual__2023-05-11T05:00:24.739667+00:00 [queued]>
[2023-05-11T05:11:41.212+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mongodb_backup.scp_to_server manual__2023-05-11T05:00:24.739667+00:00 [queued]>
[2023-05-11T05:11:41.213+0000] {taskinstance.py:1331} INFO - Starting attempt 5 of 6
[2023-05-11T05:11:41.225+0000] {taskinstance.py:1350} INFO - Executing <Task(SSHOperator): scp_to_server> on 2023-05-11 05:00:24.739667+00:00
[2023-05-11T05:11:41.232+0000] {standard_task_runner.py:57} INFO - Started process 1818 to run task
[2023-05-11T05:11:41.237+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Mongodb_backup', 'scp_to_server', 'manual__2023-05-11T05:00:24.739667+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/dagforbackup.py', '--cfg-path', '/tmp/tmpdwfmro4h']
[2023-05-11T05:11:41.238+0000] {standard_task_runner.py:85} INFO - Job 134: Subtask scp_to_server
[2023-05-11T05:11:41.319+0000] {task_command.py:410} INFO - Running <TaskInstance: Mongodb_backup.scp_to_server manual__2023-05-11T05:00:24.739667+00:00 [running]> on host b06a232a05e5
[2023-05-11T05:11:41.416+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Mongodb_backup' AIRFLOW_CTX_TASK_ID='scp_to_server' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T05:00:24.739667+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-11T05:00:24.739667+00:00'
[2023-05-11T05:11:41.418+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-11T05:11:41.476+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 172, in execute
    with self.get_ssh_client() as ssh_client:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 136, in get_ssh_client
    return self.get_hook().get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 121, in get_hook
    raise AirflowException("Cannot operate without ssh_hook or ssh_conn_id.")
airflow.exceptions.AirflowException: Cannot operate without ssh_hook or ssh_conn_id.
[2023-05-11T05:11:41.480+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Mongodb_backup, task_id=scp_to_server, execution_date=20230511T050024, start_date=20230511T051141, end_date=20230511T051141
[2023-05-11T05:11:41.490+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 134 for task scp_to_server (Cannot operate without ssh_hook or ssh_conn_id.; 1818)
[2023-05-11T05:11:41.534+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-11T05:11:41.560+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
