[2023-05-11T04:20:01.366+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mongodb_backup.test_ssh_operator scheduled__2023-05-11T04:10:00+00:00 [queued]>
[2023-05-11T04:20:01.375+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mongodb_backup.test_ssh_operator scheduled__2023-05-11T04:10:00+00:00 [queued]>
[2023-05-11T04:20:01.375+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-11T04:20:01.390+0000] {taskinstance.py:1350} INFO - Executing <Task(SSHOperator): test_ssh_operator> on 2023-05-11 04:10:00+00:00
[2023-05-11T04:20:01.398+0000] {standard_task_runner.py:57} INFO - Started process 709 to run task
[2023-05-11T04:20:01.404+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Mongodb_backup', 'test_ssh_operator', 'scheduled__2023-05-11T04:10:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/dagforbackup.py', '--cfg-path', '/tmp/tmpkstfisj3']
[2023-05-11T04:20:01.405+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask test_ssh_operator
[2023-05-11T04:20:01.480+0000] {task_command.py:410} INFO - Running <TaskInstance: Mongodb_backup.test_ssh_operator scheduled__2023-05-11T04:10:00+00:00 [running]> on host b06a232a05e5
[2023-05-11T04:20:01.529+0000] {abstractoperator.py:582} ERROR - Exception rendering Jinja template for task 'test_ssh_operator', field 'command'. Template: '/home/ubuntu/dbbackup.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 574, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/ubuntu/dbbackup.sh
[2023-05-11T04:20:01.531+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1430, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1554, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2202, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 574, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/ubuntu/dbbackup.sh
[2023-05-11T04:20:01.547+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Mongodb_backup, task_id=test_ssh_operator, execution_date=20230511T041000, start_date=20230511T042001, end_date=20230511T042001
[2023-05-11T04:20:01.558+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 74 for task test_ssh_operator (/home/ubuntu/dbbackup.sh; 709)
[2023-05-11T04:20:01.578+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-11T04:20:01.600+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
