[2023-05-10T04:43:48.475+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T04:30:00+00:00 [queued]>
[2023-05-10T04:43:48.484+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T04:30:00+00:00 [queued]>
[2023-05-10T04:43:48.485+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 3
[2023-05-10T04:43:48.498+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): run_remote_script> on 2023-05-10 04:30:00+00:00
[2023-05-10T04:43:48.504+0000] {standard_task_runner.py:57} INFO - Started process 505 to run task
[2023-05-10T04:43:48.513+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'testing_stuff', 'run_remote_script', 'scheduled__2023-05-10T04:30:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp_94pouu7']
[2023-05-10T04:43:48.515+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask run_remote_script
[2023-05-10T04:43:48.597+0000] {task_command.py:410} INFO - Running <TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T04:30:00+00:00 [running]> on host 448394b5800f
[2023-05-10T04:43:48.688+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_stuff' AIRFLOW_CTX_TASK_ID='run_remote_script' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T04:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T04:30:00+00:00'
[2023-05-10T04:43:48.691+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-10T04:43:48.693+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '#!/bin/bash\n\nssh -i ~/Downloads/3-mar-2023-N.Virginia.pem ubuntu@100.26.33.254\n\nll']
[2023-05-10T04:43:48.706+0000] {subprocess.py:86} INFO - Output:
[2023-05-10T04:43:48.727+0000] {subprocess.py:93} INFO - Warning: Identity file /home/***/Downloads/3-mar-2023-N.Virginia.pem not accessible: No such file or directory.
[2023-05-10T04:43:48.728+0000] {subprocess.py:93} INFO - Pseudo-terminal will not be allocated because stdin is not a terminal.
[2023-05-10T04:43:49.881+0000] {subprocess.py:93} INFO - Host key verification failed.
[2023-05-10T04:43:49.886+0000] {subprocess.py:93} INFO - /bin/bash: line 5: ll: command not found
[2023-05-10T04:43:49.889+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-05-10T04:43:49.925+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-05-10T04:43:49.934+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_stuff, task_id=run_remote_script, execution_date=20230510T043000, start_date=20230510T044348, end_date=20230510T044349
[2023-05-10T04:43:49.964+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 37 for task run_remote_script (Bash command failed. The command returned a non-zero exit code 127.; 505)
[2023-05-10T04:43:50.004+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-10T04:43:50.049+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
