[2023-05-09T10:18:16.268+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Bash_operator.run_remote_script manual__2023-05-09T10:05:05.541223+00:00 [queued]>
[2023-05-09T10:18:24.520+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Bash_operator.run_remote_script manual__2023-05-09T10:05:05.541223+00:00 [queued]>
[2023-05-09T10:18:24.535+0000] {taskinstance.py:1331} INFO - Starting attempt 5 of 6
[2023-05-09T10:18:24.702+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): run_remote_script> on 2023-05-09 10:05:05.541223+00:00
[2023-05-09T10:18:24.854+0000] {standard_task_runner.py:57} INFO - Started process 375 to run task
[2023-05-09T10:18:24.951+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Bash_operator', 'run_remote_script', 'manual__2023-05-09T10:05:05.541223+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/DagForBashFile.py', '--cfg-path', '/tmp/tmp3dc_2_11']
[2023-05-09T10:18:25.000+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask run_remote_script
[2023-05-09T10:18:25.416+0000] {task_command.py:410} INFO - Running <TaskInstance: Bash_operator.run_remote_script manual__2023-05-09T10:05:05.541223+00:00 [running]> on host f4c8e63ff1d9
[2023-05-09T10:18:25.950+0000] {abstractoperator.py:582} ERROR - Exception rendering Jinja template for task 'run_remote_script', field 'bash_command'. Template: '/Users/archanakarpe/Documents/saraff/MongoConnectionDags/dags/Ex01.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 574, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /Users/archanakarpe/Documents/saraff/MongoConnectionDags/dags/Ex01.sh
[2023-05-09T10:18:26.004+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1430, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1554, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2202, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 574, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /Users/archanakarpe/Documents/saraff/MongoConnectionDags/dags/Ex01.sh
[2023-05-09T10:18:26.226+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Bash_operator, task_id=run_remote_script, execution_date=20230509T100505, start_date=20230509T101816, end_date=20230509T101826
[2023-05-09T10:18:26.385+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task run_remote_script (/Users/archanakarpe/Documents/saraff/MongoConnectionDags/dags/Ex01.sh; 375)
[2023-05-09T10:18:26.560+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-09T10:18:26.745+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
