[2023-05-10T04:34:17.970+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_stuff.test_ssh_operator scheduled__2023-05-10T04:10:00+00:00 [queued]>
[2023-05-10T04:34:17.981+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_stuff.test_ssh_operator scheduled__2023-05-10T04:10:00+00:00 [queued]>
[2023-05-10T04:34:17.982+0000] {taskinstance.py:1331} INFO - Starting attempt 5 of 6
[2023-05-10T04:34:17.996+0000] {taskinstance.py:1350} INFO - Executing <Task(SSHOperator): test_ssh_operator> on 2023-05-10 04:10:00+00:00
[2023-05-10T04:34:18.002+0000] {standard_task_runner.py:57} INFO - Started process 318 to run task
[2023-05-10T04:34:18.008+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'testing_stuff', 'test_ssh_operator', 'scheduled__2023-05-10T04:10:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp85f0vnbr']
[2023-05-10T04:34:18.011+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask test_ssh_operator
[2023-05-10T04:34:18.111+0000] {task_command.py:410} INFO - Running <TaskInstance: testing_stuff.test_ssh_operator scheduled__2023-05-10T04:10:00+00:00 [running]> on host 448394b5800f
[2023-05-10T04:34:18.217+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_stuff' AIRFLOW_CTX_TASK_ID='test_ssh_operator' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T04:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T04:10:00+00:00'
[2023-05-10T04:34:18.218+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-10T04:34:18.304+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-05-10T04:34:18.329+0000] {base.py:73} INFO - Using connection ID 'ssh_conn' for task execution.
[2023-05-10T04:34:18.411+0000] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-05-10T04:34:18.994+0000] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2023-05-10T04:34:20.273+0000] {transport.py:1873} INFO - Authentication (publickey) successful!
[2023-05-10T04:34:20.276+0000] {ssh.py:476} INFO - Running command: 
dags/Ex01.sh
[2023-05-10T04:34:21.216+0000] {ssh.py:527} WARNING - bash: line 2: dags/Ex01.sh: No such file or directory
[2023-05-10T04:34:21.306+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 161, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 154, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 127
[2023-05-10T04:34:21.313+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_stuff, task_id=test_ssh_operator, execution_date=20230510T041000, start_date=20230510T043417, end_date=20230510T043421
[2023-05-10T04:34:21.337+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 29 for task test_ssh_operator (SSH operator error: exit status = 127; 318)
[2023-05-10T04:34:21.424+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-10T04:34:21.497+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
