[2023-05-10T04:57:48.927+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T04:40:00+00:00 [queued]>
[2023-05-10T04:57:48.937+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T04:40:00+00:00 [queued]>
[2023-05-10T04:57:48.938+0000] {taskinstance.py:1331} INFO - Starting attempt 4 of 5
[2023-05-10T04:57:48.963+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): run_remote_script> on 2023-05-10 04:40:00+00:00
[2023-05-10T04:57:48.975+0000] {standard_task_runner.py:57} INFO - Started process 829 to run task
[2023-05-10T04:57:48.982+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'testing_stuff', 'run_remote_script', 'scheduled__2023-05-10T04:40:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpdi6f_5yi']
[2023-05-10T04:57:48.984+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask run_remote_script
[2023-05-10T04:57:49.076+0000] {task_command.py:410} INFO - Running <TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T04:40:00+00:00 [running]> on host 448394b5800f
[2023-05-10T04:57:49.198+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_stuff' AIRFLOW_CTX_TASK_ID='run_remote_script' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T04:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T04:40:00+00:00'
[2023-05-10T04:57:49.201+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-10T04:57:49.203+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '#!/bin/bash\n\nls -lthr\npwd\ncat ~/test']
[2023-05-10T04:57:49.216+0000] {subprocess.py:86} INFO - Output:
[2023-05-10T04:57:49.230+0000] {subprocess.py:93} INFO - total 0
[2023-05-10T04:57:49.232+0000] {subprocess.py:93} INFO - /tmp/***tmpp2idh43s
[2023-05-10T04:57:49.234+0000] {subprocess.py:93} INFO - cat: /home/***/test: No such file or directory
[2023-05-10T04:57:49.235+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-10T04:57:49.256+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-10T04:57:49.262+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_stuff, task_id=run_remote_script, execution_date=20230510T044000, start_date=20230510T045748, end_date=20230510T045749
[2023-05-10T04:57:49.276+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 48 for task run_remote_script (Bash command failed. The command returned a non-zero exit code 1.; 829)
[2023-05-10T04:57:49.319+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-10T04:57:49.348+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
