[2023-05-11T05:09:20.443+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mongodb_backup.scp_to_server scheduled__2023-05-11T04:40:00+00:00 [queued]>
[2023-05-11T05:09:20.458+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mongodb_backup.scp_to_server scheduled__2023-05-11T04:40:00+00:00 [queued]>
[2023-05-11T05:09:20.459+0000] {taskinstance.py:1331} INFO - Starting attempt 5 of 6
[2023-05-11T05:09:20.474+0000] {taskinstance.py:1350} INFO - Executing <Task(SSHOperator): scp_to_server> on 2023-05-11 04:40:00+00:00
[2023-05-11T05:09:20.487+0000] {standard_task_runner.py:57} INFO - Started process 1763 to run task
[2023-05-11T05:09:20.492+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Mongodb_backup', 'scp_to_server', 'scheduled__2023-05-11T04:40:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/dagforbackup.py', '--cfg-path', '/tmp/tmp8h2i2s4s']
[2023-05-11T05:09:20.494+0000] {standard_task_runner.py:85} INFO - Job 131: Subtask scp_to_server
[2023-05-11T05:09:20.573+0000] {task_command.py:410} INFO - Running <TaskInstance: Mongodb_backup.scp_to_server scheduled__2023-05-11T04:40:00+00:00 [running]> on host b06a232a05e5
[2023-05-11T05:09:20.776+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Mongodb_backup' AIRFLOW_CTX_TASK_ID='scp_to_server' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T04:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-11T04:40:00+00:00'
[2023-05-11T05:09:20.778+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-11T05:09:20.843+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-05-11T05:09:20.859+0000] {base.py:73} INFO - Using connection ID 'ssh_conn' for task execution.
[2023-05-11T05:09:20.954+0000] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-05-11T05:09:21.516+0000] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2023-05-11T05:09:22.632+0000] {transport.py:1873} INFO - Authentication (publickey) successful!
[2023-05-11T05:09:22.635+0000] {ssh.py:476} INFO - Running command:  
scp -i ~/Downloads/3-mar-2023-N.Virginia.pem /Users/archanakarpe/Documents/saraff/MongoConnectionDags/dags/dbbackup.sh ubuntu@107.23.137.161:/home/ubuntu
[2023-05-11T05:09:23.456+0000] {ssh.py:527} WARNING - Warning: Identity file /home/ubuntu/Downloads/3-mar-2023-N.Virginia.pem not accessible: No such file or directory.
[2023-05-11T05:09:23.478+0000] {ssh.py:527} WARNING - Host key verification failed.
[2023-05-11T05:09:23.482+0000] {ssh.py:527} WARNING - lost connection
[2023-05-11T05:09:23.548+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 161, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 154, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2023-05-11T05:09:23.554+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Mongodb_backup, task_id=scp_to_server, execution_date=20230511T044000, start_date=20230511T050920, end_date=20230511T050923
[2023-05-11T05:09:23.569+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 131 for task scp_to_server (SSH operator error: exit status = 1; 1763)
[2023-05-11T05:09:23.624+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-11T05:09:23.668+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
