[2023-05-11T04:25:24.744+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mongodb_backup.test_ssh_operator scheduled__2023-05-11T03:40:00+00:00 [queued]>
[2023-05-11T04:25:24.754+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mongodb_backup.test_ssh_operator scheduled__2023-05-11T03:40:00+00:00 [queued]>
[2023-05-11T04:25:24.754+0000] {taskinstance.py:1331} INFO - Starting attempt 7 of 8
[2023-05-11T04:25:24.767+0000] {taskinstance.py:1350} INFO - Executing <Task(SSHOperator): test_ssh_operator> on 2023-05-11 03:40:00+00:00
[2023-05-11T04:25:24.777+0000] {standard_task_runner.py:57} INFO - Started process 831 to run task
[2023-05-11T04:25:24.785+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Mongodb_backup', 'test_ssh_operator', 'scheduled__2023-05-11T03:40:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dagforbackup.py', '--cfg-path', '/tmp/tmpclkkqw0q']
[2023-05-11T04:25:24.787+0000] {standard_task_runner.py:85} INFO - Job 85: Subtask test_ssh_operator
[2023-05-11T04:25:24.869+0000] {task_command.py:410} INFO - Running <TaskInstance: Mongodb_backup.test_ssh_operator scheduled__2023-05-11T03:40:00+00:00 [running]> on host b06a232a05e5
[2023-05-11T04:25:24.977+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Mongodb_backup' AIRFLOW_CTX_TASK_ID='test_ssh_operator' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T03:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-11T03:40:00+00:00'
[2023-05-11T04:25:24.978+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-11T04:25:25.047+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-05-11T04:25:25.067+0000] {base.py:73} INFO - Using connection ID 'ssh_conn' for task execution.
[2023-05-11T04:25:25.135+0000] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-05-11T04:25:25.698+0000] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2023-05-11T04:25:26.841+0000] {transport.py:1873} INFO - Authentication (publickey) successful!
[2023-05-11T04:25:26.843+0000] {ssh.py:476} INFO - Running command: 
echo 'Running shell script'
sudo su -
/home/ubuntu/dbbackup.sh
[2023-05-11T04:25:27.776+0000] {ssh.py:522} INFO - Running shell script
[2023-05-11T04:25:28.056+0000] {ssh.py:527} WARNING - bash: line 4: /home/ubuntu/dbbackup.sh: Permission denied
[2023-05-11T04:25:28.097+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 161, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 154, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 126
[2023-05-11T04:25:28.102+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Mongodb_backup, task_id=test_ssh_operator, execution_date=20230511T034000, start_date=20230511T042524, end_date=20230511T042528
[2023-05-11T04:25:28.115+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 85 for task test_ssh_operator (SSH operator error: exit status = 126; 831)
[2023-05-11T04:25:28.184+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-11T04:25:28.215+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
